// <auto-generated />
using System;
using Ikea.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ikea.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ikea.Domain.Entities.Colour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Colours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Turquoise"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Teal"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Maroon"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Mint"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Coral"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Indigo"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Magenta"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Violet"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Cyan"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Burgundy"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lavender"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Cream"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Charcoal"
                        });
                });

            modelBuilder.Entity("Ikea.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ikea.Domain.Entities.ProductColour", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ColourId");

                    b.HasIndex("ColourId");

                    b.ToTable("ProductColours");
                });

            modelBuilder.Entity("Ikea.Domain.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chair"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Table"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bed"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sofa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bookshelf"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Desk"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wardrobe"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dresser"
                        },
                        new
                        {
                            Id = 9,
                            Name = "TV Stand"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Coffee Table"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Dining Set"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nightstand"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Armchair"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Kitchen Cabinet"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bathroom Vanity"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Storage Unit"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Lamp"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Rug"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Mirror"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Picture Frame"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Plant Pot"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Curtains"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Pillow"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Blanket"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Mattress"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Office Chair"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Shelf Unit"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Side Table"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Dining Chair"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Stool"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Room Divider"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Wall Shelf"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Kitchen Island"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Bar Stool"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Daybed"
                        });
                });

            modelBuilder.Entity("Ikea.Domain.Entities.Product", b =>
                {
                    b.HasOne("Ikea.Domain.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Ikea.Domain.Entities.ProductColour", b =>
                {
                    b.HasOne("Ikea.Domain.Entities.Colour", "Colour")
                        .WithMany("ProductColours")
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ikea.Domain.Entities.Product", "Product")
                        .WithMany("ProductColours")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ikea.Domain.Entities.Colour", b =>
                {
                    b.Navigation("ProductColours");
                });

            modelBuilder.Entity("Ikea.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductColours");
                });

            modelBuilder.Entity("Ikea.Domain.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
